export const types = {
  HERO_ANIMATE: 'HERO_ANIMATE',
  CHANGE_LANG: 'CHANGE_LANG',
  TAB_NUM: 'TAB_NUM',
  TICK: 'TICK',
  GET_FPS: 'GET_FPS',
  LOAD_FOLIO: 'LOAD_FOLIO',
  GO_TO_FOLIO: 'GO_TO_FOLIO',
  GO_TO_HOME: 'GO_TO_HOME',
  TAB_MODIFY: 'TAB_MODIFY',
};
